### ISSUE TITLE
ダークモードだと背景が黒くなってしまいデザインが見えづらくなる

### ISSUE THREAD

**Issue by jacopen** [cniajp/cnia.io#3]
ダークモードの考慮が漏れているため、ダークモードで表示すると背景が黒くなってしまいロゴ等が見えづらくなる。

ダークモード両対応はコストがかかるので、どのモードであっても白背景で表示されるようにする

**Comment by tanayan299** [comment]
https://github.com/cniajp/cnia.io/pull/8 にて対応。
